export const products = [
  {
    id: '1',
    slug: 'product-1',
    name: '코지 서랍장',
    subtitle: '아동용 3단 원목 서랍장',
    price: 420000,
    image: '/baby_drawer_organizer_1775743106219.png',
    category: '수납',
    description: '유럽산 자작나무 합판으로 제작된 아동용 3단 서랍장입니다. 부드러운 라운드 엣지와 소프트 클로징 레일로 아이의 안전을 지켜줍니다. 깔끔한 디자인으로 어떤 인테리어에도 잘 어울립니다.',
    specs: [
      { label: '소재', value: '유럽산 자작나무 합판' },
      { label: '사용 연령', value: '3세 ~ 12세' },
      { label: '크기', value: 'W600 × D400 × H900 mm' },
      { label: '무게', value: '22kg' },
    ],
    options: null,
    accordion: [
      { title: '배송 및 조립 정보', content: '무료 배송 (7~14 영업일 소요)<br>도서산간 지역 추가 비용 없음<br>조립 서비스 이용 가능 (+₩50,000)' },
      { title: '교환 / 반품 안내', content: '수령 후 14일 이내 교환/반품 가능<br>조립 완료 제품은 교환/반품 불가<br>고객센터: 1588-0000' },
    ],
  },
  {
    id: '2',
    slug: 'product-2',
    name: '포레스트 독서대',
    subtitle: '각도 조절 아동 독서대',
    price: 280000,
    image: '/high_chair_minimalist_1775743035981.png',
    category: '학습',
    description: '아이의 바른 자세를 위한 각도 조절 독서대입니다. 천연 너도밤나무 원목을 사용하였으며, 12단계 각도 조절과 넓은 받침대로 편안한 독서 환경을 제공합니다.',
    specs: [
      { label: '소재', value: '너도밤나무 원목' },
      { label: '사용 연령', value: '5세 ~ 성인' },
      { label: '크기', value: 'W450 × D350 × H380 mm' },
      { label: '각도', value: '12단계 조절 (0°~60°)' },
    ],
    options: null,
    accordion: [
      { title: '배송 및 조립 정보', content: '무료 배송 (5~10 영업일 소요)<br>완제품 배송 (조립 불필요)' },
      { title: '교환 / 반품 안내', content: '수령 후 14일 이내 교환/반품 가능<br>고객센터: 1588-0000' },
    ],
  },
  {
    id: '3',
    slug: 'product-3',
    name: '노르딕 슈벤치',
    subtitle: '현관 수납형 신발 벤치',
    price: 195000,
    image: '/crib_premium_1775742557844.png',
    category: '현관',
    description: '현관을 깔끔하게 정리해주는 수납형 슈벤치입니다. 상단은 편안한 좌석으로, 하단에는 신발 4~6켤레를 수납할 수 있습니다. 원목 프레임과 패브릭 쿠션의 조화가 따뜻한 분위기를 만들어줍니다.',
    specs: [
      { label: '소재', value: '오크 원목 + 폴리에스터 쿠션' },
      { label: '수납', value: '신발 4~6켤레' },
      { label: '크기', value: 'W800 × D350 × H450 mm' },
      { label: '하중', value: '최대 80kg' },
    ],
    options: null,
    accordion: [
      { title: '배송 및 조립 정보', content: '무료 배송 (7~14 영업일 소요)<br>간단 조립 (약 15분)' },
      { title: '교환 / 반품 안내', content: '수령 후 14일 이내 교환/반품 가능<br>고객센터: 1588-0000' },
    ],
  },
  {
    id: '4',
    slug: 'product-4',
    name: '라운디 교구장',
    subtitle: '아동 교구·장난감 정리장',
    price: 380000,
    image: '/baby_drawer_organizer_1775743106219.png',
    category: '수납',
    description: '아이의 교구와 장난감을 깔끔하게 정리할 수 있는 오픈형 교구장입니다. 라운드 모서리로 안전하고, 다양한 크기의 칸막이로 자유롭게 수납할 수 있습니다. 하단 이동식 바구니로 정리가 쉬워집니다.',
    specs: [
      { label: '소재', value: '자작나무 합판 + MDF' },
      { label: '사용 연령', value: '2세 ~ 8세' },
      { label: '구성', value: '선반 3단 + 이동식 바구니 2개' },
      { label: '크기', value: 'W900 × D350 × H800 mm' },
    ],
    options: null,
    accordion: [
      { title: '배송 및 조립 정보', content: '무료 배송 (7~14 영업일 소요)<br>조립 서비스 이용 가능 (+₩40,000)' },
      { title: '교환 / 반품 안내', content: '수령 후 14일 이내 교환/반품 가능<br>조립 완료 제품은 교환/반품 불가<br>고객센터: 1588-0000' },
    ],
  },
  {
    id: '5',
    slug: 'product-5',
    name: '미니멀 책장',
    subtitle: '아동 책장 (2단/3단 선택)',
    price: 240000,
    image: '/high_chair_minimalist_1775743035981.png',
    category: '수납',
    description: '심플하고 모던한 디자인의 아동 책장입니다. 2단과 3단 중 공간에 맞게 선택할 수 있으며, 전면 디스플레이 선반으로 아이가 스스로 책을 고를 수 있도록 도와줍니다.',
    specs: [
      { label: '소재', value: '파인우드 원목 + MDF' },
      { label: '사용 연령', value: '2세 ~ 10세' },
      { label: '크기 (2단)', value: 'W700 × D300 × H600 mm' },
      { label: '크기 (3단)', value: 'W700 × D300 × H900 mm' },
    ],
    options: [
      { label: '2단', price: 240000 },
      { label: '3단', price: 310000 },
    ],
    accordion: [
      { title: '배송 및 조립 정보', content: '무료 배송 (7~14 영업일 소요)<br>간단 조립 (약 20분)' },
      { title: '교환 / 반품 안내', content: '수령 후 14일 이내 교환/반품 가능<br>고객센터: 1588-0000' },
    ],
  },
];
